# Generated by Django 4.2.5 on 2023-10-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordsToTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_word', models.CharField(max_length=50)),
                ('kpos', models.CharField(max_length=20)),
                ('epos', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('k_word', 'kpos')},
            },
        ),
    ]
