# Generated by Django 4.2.5 on 2023-12-29 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wordstotranslate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wordstotranslate',
            name='e_sentence',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wordstotranslate',
            name='e_translation',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
