# Generated by Django 4.2.5 on 2023-12-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0002_alter_wordstotranslate_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordstotranslate',
            name='id',
        ),
        migrations.AddField(
            model_name='wordstotranslate',
            name='custom_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
